# TO profile zsh' stratup time
# zmodload zsh/zprof

# where is antibody keeping its stuff?
ANTIBODY_HOME="$(antibody home)"

# tell omz where it lives
export ZSH="$ANTIBODY_HOME"/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh

# Powerlevel9k configuration
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon root_indicator context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time)
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
DEFAULT_USER="$USER"

# Stop Oh-My-Zsh from prompting for update
DISABLE_AUTO_UPDATE="true"

# Load the plugins generated by Antibody
# Regenerate with `antibody bundle < ~/.zsh_plugins.txt >! ~/.zsh_plugins.sh`
source ~/.zsh_plugins.sh

# Reload completions
autoload -U compinit && compinit

# Keybindings - from the sane defaults in /etc/inputrc
bindkey "\e[1~" beginning-of-line
bindkey "\e[4~" end-of-line
bindkey "\e[5~" beginning-of-history
bindkey "\e[6~" end-of-history
bindkey "\e[7~" beginning-of-line
bindkey "\e[3~" delete-char
bindkey "\e[2~" quoted-insert
bindkey "\e[5C" forward-word
bindkey "\e[5D" backward-word
bindkey "\e\e[C" forward-word
bindkey "\e\e[D" backward-word
bindkey "\e[1;5C" forward-word
bindkey "\e[1;5D" backward-word
bindkey "\e[8~" end-of-line
bindkey "\eOH" beginning-of-line
bindkey "\eOF" end-of-line
bindkey "\e[H" beginning-of-line
bindkey "\e[F" end-of-line

# fasd init
eval "$(fasd --init auto)"

# Zsh startup time profiling
# zprof
